create database Inventario;
use Inventario;
create table Personal (
	id int primary key not null auto_increment,
    Nombre varchar(80) not null,
    Contraseña varchar (20) not null
);
create table Material (
	id int not null primary key auto_increment,
    Nombre text not null,
    Tipo varchar(80) not null,
    Marca Varchar(80) not null,
    Modelo varchar(80) not null,
    Serie varchar(80) not null,
    Cantidad int not null,
    Ubicacion text not null,
    Especificaciones text not null
);
Create table Historial (
	id int not null primary key auto_increment,
    Fecha_I date not null,
    Fecha_F date,
    Nombre Varchar(100) not null,
    Matricula varchar(10) not null,
    id_Material int not null,
    Cantidad int not null,
    Devuelto TINYINT(1),
    foreign key (id_Material) references Material (id)
);

/*Insertar elementos de tipo Cristal*/
Insert into Material
values (0, 'FRASCO AMBAR BOCA ANCHA 250 ML' , 'Cristal', 'SD', 'SD', 'SD', 24, 'LABORATORIO DE QUIMICA', 'VIDRIO COLOR AMBAR'),
(0, 'KIT MATRAZ ERLENMEYER GRADUADO 50, 125, 250, 500 Y 1000 ML', 'Cristal', 'PYREX', 'SD', 'SD', 2, 'LABORATORIO DE QUIMICA', 'VIDRIO'),
(0, 'KIT PROBETA 10, 25, 50, 100 Y 250 ML', 'Cristal', 'KIMAX', 'SD', 'SD', 2, 'LABORATORIO DE QUIMICA', 'VIDRIO, GRADUADO'),
(0, 'MATRAZ FLORENCIA250 ML ', 'Cristal', 'PYREX', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'VIDRIO'),
(0, 'MATRAZ KITAZATO PARA FILTRACION 250 ML', 'Cristal', 'KIMAX', 'SD', 'SD', 2, 'LABORATORIO DE QUIMICA', 'VIDRIO, CON CONEXÍON PARA TUBO DE LATEX'),
(0, 'PIPETA SEROLOGICA 7085-10X1', 'Cristal', 'PYREX', 'SD', 'SD', 5, 'LABORATORIO DE QUIMICA', 'VIDRIO, GRADUADA'),
(0, 'VASO DE PRECIPITADO  100 ML', 'Cristal', 'KIMAX', 'SD', 'SD', 2, 'LABORATORIO DE QUIMICA', 'VIDRIO'),
(0, 'VASO DE PRECIPITADO  250 ML', 'Cristal', 'KIMAX', 'SD', 'SD', 2, 'LABORATORIO DE QUIMICA', 'VIDRIO'),
(0, 'VASO DE PRECIPITADOS 50 ML', 'Cristal', 'KIMAX', 'SD', 'SD', 2, 'LABORATORIO DE QUIMICA', 'VIDRIO'),
(0, 'VASO DE PRECIPITADO DE VIDRIO 1000 ML', 'Cristal', 'KIMAX', 'SD', 'SD', 2, 'LABORATORIO DE QUIMICA', 'VIDRIO'),
(0, 'VASO DE PRECIPITADO DE VIDRIO 600 ML', 'Cristal', 'KIMAX', 'SD', 'SD', 2, 'LABORATORIO DE QUIMICA', 'VIDRIO'),
(0, 'BURETA GRADUADA 50 ML', 'Cristal', 'CIVEQ', 'SD', 'SD', 4, 'LABORATORIO DE QUIMICA', 'CRISTAL, GRADUADA'),
(0, 'EMBUDO ESTIRADO 60° 65 MM', 'Cristal', 'PYREX', 'SD', 'SD', 5, 'LABORATORIO DE QUIMICA', 'VIDRIO'),
(0, 'TUBO DE CULTIVO S/LABIO, PQT CON 249 PZAS', 'Cristal', 'PYREX', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'CRISTAL'),
(0, 'KIT DE CILINDRO GRADUADO CLASE B  10, 25, 50, 100 Y 250 ML', 'Cristal', 'KIMAX', '20024-01', 'SD', 2, 'LABORATORIO DE QUIMICA', 'DE VIDIRO, CON GRADUACIÓN '),
(0, 'MATRAZ VOLUMETRICO DE VIDRIO BORISILICATO CON TAPÓN DE PP.  250 ML', 'Cristal', 'SD', 'SD', 'SD', 2, 'LABORATORIO DE QUIMICA', 'CUELLO LARGO'),
(0, 'PAQUETE VARIADO DE MATRAZ ERLENMEYER  DE 50, 125, 250, 500 Y 1 L', 'Cristal', 'CORNING', 'SD', 'SD', 3, 'LABORATORIO DE QUIMICA', 'VIDRIO'),
(0, 'MATRAZ VOLUMETRICO DE VIDRIO CON TAPA DE VIDRIO DE 250 ML', 'Cristal', 'PYREX', '5640-250', 'SD', 6, 'LABORATORIO DE QUIMICA', 'CUELLO LARGO'),
(0, 'MATRAZ DE FILTRADO DE 500 ML', 'Cristal', 'PYREX', '5340-500', 'SD', 3, 'LABORATORIO DE QUIMICA', 'VIDRIO CON CONEXIÓN PARA TUBO DE LATEX'),
(0, 'PORTAOBJETOS DIAMANTADO CAJA C/50 ', 'Cristal', 'SD', '2947-25X75', 'SD', 20, 'LABORATORIO DE QUIMICA', 'VIDRIO, EN CAJA BLANCA'),
(0, 'MATRAZ DE EBULLICIÓN FONDO REDONDO', 'Cristal', 'PYREX', 'SD', 'SD', 6, 'LABORATORIO DE QUIMICA', 'DE VIDRIO'),
(0, 'BOTELLAS DE VIDRIO AMBAR DE BOCA ANGOSTA DE 250 ML', 'Cristal', 'THERMO SCIENTIFIC', '329-250', 'SD', 12, 'LABORATORIO DE QUIMICA', 'VIDRIO COLOR AMBAR, TAPA CHICA'),
(0, 'VIDRIO DE RELOJ 100MM', 'Cristal', 'PYREX', 'SD', 'SD', 10, 'LABORATORIO DE QUIMICA', 'VIDRIO CÓNCAVO'),
(0, 'EMBUDO DE VIDRIO PARA FILTRADO KIMEX DE 55 MM DE DIAM. SUPERIOR', 'Cristal', 'KIMBLE CHASE', '28950-55', 'SD', 12, 'LABORATORIO DE QUIMICA', 'VIIDRIO'),
(0, 'CUBREOBJETOS, CAJA C/100', 'Cristal', 'SD', '2865-22X22', 'SD', 10, 'LABORATORIO DE QUIMICA', 'EN CAJA PROTECTORA'),
(0, 'VIDRIO DE RELOJ 100MM', 'Cristal', 'UNITED SCIENTIFIC', 'SD', 'SD', 12, 'LABORATORIO DE QUIMICA', 'VIDRIO CÓNCAVO'),
(0, 'FRASCO TARRO DE BOCA ANCHA DE 250 ML', 'Cristal', 'SD', '5220845C21', 'SD', 10, 'LABORATORIO DE QUIMICA', 'VIDRIO COLOR AMBAR'),
(0, 'CRSITALIZADOR 180 ml', 'Cristal', 'PYREX', '3140-80X40', 'SD', 5, 'LABORATORIO DE QUIMICA', 'DE VIDRIO, DE 3 CM DE ALTURA');

/*Insertar elementos de tipo Metal gas*/
Insert into Material values (0, 'PINZA PARA MATRAZ', 'Metal_Gas', 'SD', 'SD', 'SD', 2, 'LABORATORIO DE QUIMICA', 'PINZA DE METAL')
,(0, 'ESTADAL DE ALUMINIO TELESCOPICO 4m.', 'Metal_Gas', 'SD', 'SD', 'SD', 4, 'LABORATORIO DE QUIMICA', 'EN FUNDA ROJA DE LONA')
,(0, 'MICROTOMO CON NAVAJA ', 'Metal_Gas', 'SD', 'HM1/HM1A', 'SD', 3, 'LABORATORIO DE QUIMICA', 'DE METAL CON SUPERFICIE DE CERAMICA, EN CAJA BLANCA')
,(0, 'MECHERO FISHER ALTA TEMPERATURA', 'Metal_Gas', 'SD', 'SD', 'SD', 5, 'LABORATORIO DE QUIMICA', 'METAL')
,(0, 'SOPORTE UNIVERSAL CON VARILLA DE 60 CMS', 'Metal_Gas', 'CIVEQ', 'CVQ-0012', 'SD', 5, 'LABORATORIO DE QUIMICA', 'DE ACERO, CON VARILLA CROMADA')
,(0, 'SOPORTE RECTANGULAR CON BASE DE ACERO Y VARILLA DE 36 X 1/2 "', 'Metal_Gas', 'DAIGGER', 'EF23185F', 'SD', 5, 'LABORATORIO DE QUIMICA', 'DE ACERO, CON VARILLA CROMADA')
,(0, 'TRIPIE DE FIERRO DESMONTABLE', 'Metal_Gas', 'CIVEQ', 'SD', 'SD', 5, 'LABORATORIO DE QUIMICA', 'DE FIERRO, CON PATAS PARA ENSAMBLAR')
,(0, 'MECHERO TIPO TIRRIL', 'Metal_Gas', 'SD', 'SD', 'SD', 5, 'LABORATORIO DE QUIMICA', 'METAL')
,(0, 'SOPORTE DE TRIPIE CON ANILLO O DE 6"', 'Metal_Gas', 'UNITED SCIENTIFIC SUPPLY', 'H24160', 'SD', 5, 'LABORATORIO DE QUIMICA', 'ANILLO DE METAL CON PATAS DE ACERO')
,(0, 'TELA DE ALAMBRE CENTRO DE CERÁMICA ', 'Metal_Gas', 'QUIVEQ', 'SD', 'SD', 10, 'LABORATORIO DE QUIMICA', 'MALLA DE METAL CON CENTRO DE CERAMICA');

/*Insertar elementos de tipo Polimeros*/
Insert into Material values (0, 'PICETA DE POLIPROPILENO 500 ML', 'Polimero', 'SD', 'SD', 'SD', 7, 'LABORATORIO DE QUIMICA', 'DE PLÁSTICO TRANSPARENTE')
, (0, 'PINZA DOBLE PARA BURETA ', 'Polimero', 'CIVEQ', 'CVQ-0126', 'SD', 5, 'LABORATORIO DE QUIMICA', 'PLÁSTICO BLANCO')
, (0, 'TUBO DE HULE LATEX AMBAR PARA MECHERO 6MM/9MM, CAJA 15 METROS', 'Polimero', 'XTEVQ', 'SD', 'SD', 4, 'LABORATORIO DE QUIMICA', 'MANGUERA DE LATEX EN CAJA')
, (0, 'SOPORTE PARA EMBUDO BUCHNER, PAQUETE CON 7 SOPORTES DE NEOPRENO', 'Polimero', 'DYNALON', '242864-0000', 'SD', 4, 'LABORATORIO DE QUIMICA', 'GRIS, DE NEOPRENO')
, (0, 'CAJA DE POLIPROPILENO PARA TRANSPORTE DE PORTAOJETOS', 'Polimero', 'SD', 'SD', 'SD', 2, 'LABORATORIO DE QUIMICA', 'DE PLÁSTICO, AZUL')
, (0, 'FRASCO LAVADOR DE 500 ML', 'Polimero', 'SD', 'SD', 'SD', 5, 'LABORATORIO DE QUIMICA', 'DE PLÁSTICO TRANSPARENTE');

/*Insertar elementos de tipo Porcelana*/
Insert into Material values (0, 'EMBUDO BUCHNER', 'Porcela', 'DUBE CAT', 'CVQ-3090', 'SD', 5, 'LABORATORIO DE QUIMICA', 'DE PORCELANA, BLANCO')
, (0, 'CÁPSULA DE PORCELANA DE 100 ML', 'Porcela', 'SD', 'SD', 'SD', 4, 'LABORATORIO DE QUIMICA', 'BLANCA, DE PORCELANA')
, (0, 'EMBUDO BUCHNER DE PORCELANA 63MM ANCHO 101 MM ALTO', 'Porcela', 'COORSTEK', '602040', 'SD', 4, 'LABORATORIO DE QUIMICA', 'DE PORCELANA, BLANCO')
, (0, 'MORTERO DE PORCELANA 20 ML CON PISTILO', 'Porcela', 'SD', 'SD', 'SD', 5, 'LABORATORIO DE QUIMICA', 'CERÁMICA BLANCA')
, (0, 'CÁPSULA DE PORCELANA 70 ML', 'Porcela', 'COORS TEK', '60197', 'SD', 3, 'LABORATORIO DE QUIMICA', 'BLANCA, DE PORCELANA');

/*Insertar elementos de tipo Equipo Electrico*/
Insert into Material values (0, 'CENTRIFUGA UNIVERSAL CLINICA DIGITAL DE 8 TUBOS', 'Equipo_Electrico', 'VELAB', 'VE-4000', 'SD', 1, 'LABORATORIO DE QUIMICA', 'PLASTICO BLANCA Y AZUL')
, (0, 'TEODOLITO ELECTRONICO CON TRIPIE', 'Equipo_Electrico', 'SOUTH', 'ET05', 'G001-J003-D004', 1, 'LABORATORIO DE QUIMICA', 'EN ESTUCHE ROJO, COLO AMARILLO')
, (0, 'MICROSCOPIO TRINOCULAR', 'Equipo_Electrico', 'SD', '86041', 'SD', 4, 'LABORATORIO DE QUIMICA', 'DE METAL, BLANCO CON FUNDA')
, (0, 'PARRILLA CON AGITACION', 'Equipo_Electrico', 'CORNING', 'PC-620D', 'SD', 3, 'LABORATORIO DE QUIMICA', 'SD')
, (0, 'MICROSCOPIO BINOCULAR BIOLOGICO', 'Equipo_Electrico', 'VELAB MICROSCOPES', 'VE-B1', '150128-119', 3, 'LABORATORIO DE QUIMICA', 'BLANCO CON AZUL, CON FUNDA DE PLASTICO')
, (0, 'BALANZA PORTATIL DE 600gr.', 'Equipo_Electrico', 'OHAUS', 'SP601', '8336028191', 3, 'LABORATORIO DE QUIMICA', 'PORTATIL CON CABLE ')
, (0, 'MEDIDOR DE PH IMPERMEABLE', 'Equipo_Electrico', 'HANNA INSTRUMENTS', 'HI98128', 'SD', 4, 'LABORATORIO DE QUIMICA', 'EN CAJA, COLOR ROJO DE PLASTICO')
, (0, 'MICROSCOPIO ESTEREOSCOPICO', 'Equipo_Electrico', 'KONUS', 'AMBER 5033', 'SD', 6, 'LABORATORIO DE QUIMICA', 'COLOR AMBAR, DE PLASTICO,  DE BATERÍAS, PEQUEÑO');

/*Insertar elementos de tipo Material_Imantado*/
Insert into Material values  (0, 'AGITADOR MAGNETICO', 'Material_Imantado', 'SCIENTIFIC', 'CVP-3250C', '201501066', 3, 'LABORATORIO DE QUIMICA', 'BLANCO, DE PLASTICO')
, (0, 'BARRAS MAGNETICAS DE AGITACION 1/2" X 5/16"', 'Material_Imantado', 'SPINBAR', 'SD', 'SD', 10, 'LABORATORIO DE QUIMICA', 'DE TEFLÓN, EN PAQUETE')
, (0, 'BARRA DE AGITACIÓN  MAGNETICA OCTAGONAL', 'Material_Imantado', 'VWR', 'SD', 'SD', 10, 'LABORATORIO DE QUIMICA', 'TEFLON GRIS, EN SU PAQUETE');

/*Insertar elementos de tipo Seguridad*/
Insert into Material values (0, 'GUANTE DE ASBESTO', 'Seguridad', 'NACIONAL', 'SD', 'SD', 4, 'LABORATORIO DE QUIMICA', 'AZUL CLARO, DE TELA')
, (0, 'GAFAS DE SEGURIDAD', 'Seguridad', 'SD', 'SD', 'SD', 16, 'LABORATORIO DE QUIMICA', 'MICA TRANSPARENTE CON ARMAZON AZUL,BLANCO Y ROJO')
, (0, 'GOGLE LENTE DE SEGURIDAD TIPO MEDICAL', 'Seguridad', 'SD', 'SD', 'SD', 30, 'LABORATORIO DE QUIMICA', 'MICA RESISTENTE COMPLETAMENTE TRANSPARENTES')
, (0, 'MANDIL ', 'Seguridad', 'SD', 'SD', 'SD', 3, 'LABORATORIO DE QUIMICA', 'MANDIL DE VINIL BLANCO');

/*Insertar elementos de tipo Sustancias*/
Insert into Material values (0, 'KIT PARA ANALISIS DE SUELOS', 'Sustancias', 'LAMOTT', 'STH-14', 'SD', 1, 'LABORATORIO DE QUIMICA', 'MALETIN NEGRO DURO')
, (0, 'AZUL DE TOLOUIDINA DE 25 GR', 'Sustancias', 'CIVEQ', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'BOTELLA CON ETIQUETA')
, (0, 'SULFATO MANGANOSO MONOHIDRATADO, 500 GR', 'Sustancias', 'FREEMONT', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'EN FRASCO CON ETIQUETA')
, (0, 'ACIDO BORICO, SOL AL 1%', 'Sustancias', 'HYCEL', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'BOTELLA CON ETIQUETA')
, (0, 'ACIDO NÍTRICO AL 64 - 66%,  1 LT', 'Sustancias', 'FREEMONT', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'BOTELLA CON ETIQUETA')
, (0, 'VIOLETA CRISTAL GENCIANA EC, 100 GR ', 'Sustancias', 'CIVEQ', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'EN FRASCO CON ETIQUETA')
, (0, 'HIDROXIDO DE SODIO, 500 GR', 'Sustancias', 'FREEMONT', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'EN FRASCO CON ETIQUETA')
, (0, 'HIDROXIDO DE SODIO, 500 GR', 'Sustancias', 'FREEMONT', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'EN FRASCO CON ETIQUETA')
, (0, 'SAFRANINA SOL ACUOSA 1%, 500 ML', 'Sustancias', 'CIVEQ', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'EN FRASCO CON ETIQUETA')
, (0, 'EOSINA AMARILLENTA SOL. 1% OH, 500 ML', 'Sustancias', 'CIVEQ', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'EN FRASCO CON ETIQUETA')
, (0, 'VERDE BRILLANTE, SOL ACUOSA 1% 500 ML', 'Sustancias', 'HYCEL', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'EN FRASCO CON ETIQUETA')
, (0, 'AZUL DE METILENO SOL ACUOSA 1%', 'Sustancias', 'CIVEQ', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'BOTELLA CON ETIQUETA')
, (0, 'NARANJA METILO 0.05 0.1%, 500 ML', 'Sustancias', 'HYCEL', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'EN FRASCO CON ETIQUETA')
, (0, 'NITRATO DE CALCIO', 'Sustancias', 'SD', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'EN FRASCO CON ETIQUETA')
, (0, 'HIERRO (III) CLORURO HEXAHIDRATO', 'Sustancias', 'SD', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'EN FRASCO CON ETIQUETA')
, (0, 'MAGNESIO EN CINTA', 'Sustancias', 'SD', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'MAGNESIO EN CINTA 0.15 A 0.30 MM DE ESPESOR 3MM')
, (0, 'ACIDO SALICILICO', 'Sustancias', 'SD', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'ACIDO SALISILICO, GRADO U.S.P. ANHIDRIDO')
, (0, 'FIERRO METALICO', 'Sustancias', 'SD', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'REACTIVO EN FORMA DE POLVO');

/*Insertar elementos de tipo Limpieza*/
Insert into Material values (0, 'ESCOBILLON PARA BURETA 65X15X1.5', 'Limpieza', 'SD', 'SD', 'SD', 5, 'LABORATORIO DE QUIMICA', 'S/D')
,(0, 'ESCOBILLON PARA TUBO DE ENSAYO 15X7X1.5', 'Limpieza', 'SD', 'SD', 'SD', 3, 'LABORATORIO DE QUIMICA', 'S/D')
,(0, 'ESCOBILLÓN PARA MATRAZMED 37X11X15', 'Limpieza', 'SD', 'SD', 'SD', 12, 'LABORATORIO DE QUIMICA', 'S/D');

/*Insertar elementos de tipo Consumibles*/
Insert into Material values(0, 'PAPEL PARAFILM 10 CM X 38 METROS', 'Consumibles', 'SD', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'CAJA DISPENSADORA')
,(0, 'PAPEL FILTRO #1 12.5 CM C/100 PZAS', 'Consumibles', 'WHATMAN', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'EN CAJA')
,(0, 'PAPEL FILTRO #1 12.5 CM C/100 PZAS', 'Consumibles', 'WHATMAN', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'EN CAJA')
,(0, 'PAPEL FILTRO 12.5 CM, DE 11 MICRAS, PAQ. CON 100 PIEZAS', 'Consumibles', 'WHATMAN', '1001-125', 'SD', 1, 'LABORATORIO DE QUIMICA', 'EN CAJA')
,(0, 'PAPEL INDICADOR DE PH -14, CON 100 TIRAS', 'Consumibles', 'FREEMONT', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'CAJA DISPENSADORA DE PLÁSTICO')
,(0, 'PAPEL INDICADOR DE PH -14, CON 100 TIRAS', 'Consumibles', 'FREEMONT', 'SD', 'SD', 1, 'LABORATORIO DE QUIMICA', 'CAJA DISPENSADORA DE PLÁSTICO');

/*Insertar el unico usuario disponible*/
insert into Personal values (0,'Tec Mante','Tecky');